name: Build

on:
  push:
    tags:
      - 'v*'

env:
  IS_CI: 'true'

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v6

      - name: Get npm cache directory
        shell: pwsh
        run: echo "NPM_CACHE=$(npm config get cache)" >> $env:GITHUB_ENV

      - name: Setup Node Env
        env:
          NPM_CACHE: ${{ env.NPM_CACHE }}
        uses: ./.github/actions/setup

      - name: Build src code
        run: npm run build

      - name: Build packages
        run: |
          npm run pack:win:7z:x64
          npm run pack:win:setup:x64
          npm run pack:win:setup:arm64
          npm run pack:win:7z:arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: windows-packages
          path: build/*.{exe,7z}

      - name: Generate file MD5
        run: |
          cd build
          Get-FileHash *.exe,*.7z -Algorithm MD5 | Format-List

  Mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v6

      - name: Install python3 setuptools
        run: brew install python-setuptools

      - name: Get npm cache directory
        shell: bash
        run: echo "NPM_CACHE=$(npm config get cache)" >> $GITHUB_ENV

      - name: Setup Node Env
        env:
          NPM_CACHE: ${{ env.NPM_CACHE }}
        uses: ./.github/actions/setup

      - name: Build src code
        run: npm run build

      - name: Build packages
        run: |
          npm run pack:mac:dmg
          npm run pack:mac:dmg:arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: mac-packages
          path: build/*.dmg

      - name: Generate file MD5
        run: |
          cd build
          md5 *.dmg

  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y rpm libarchive-tools

      - name: Check out git repository
        uses: actions/checkout@v6

      - name: Get npm cache directory
        shell: bash
        run: echo "NPM_CACHE=$(npm config get cache)" >> $GITHUB_ENV

      - name: Setup Node Env
        env:
          NPM_CACHE: ${{ env.NPM_CACHE }}
        uses: ./.github/actions/setup

      - name: Build src code
        run: npm run build

      - name: Build packages
        run: |
          npm run pack:linux:deb:amd64
          npm run pack:linux:deb:arm64
          npm run pack:linux:deb:armv7l
          npm run pack:linux:appImage
          npm run pack:linux:rpm
          npm run pack:linux:pacman

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: linux-packages
          path: build/*.{deb,AppImage,rpm,pacman}

      - name: Generate file MD5
        run: |
          cd build
          md5sum *.deb *.rpm *.pacman *.AppImage

  Release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [Windows, Mac, Linux]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: packages

      - name: Display structure
        run: ls -R packages

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
